server:
  port: 8761
eureka:
  client:
    serviceUrl:
      defaultZone: ${DISCOVERY_URL:http://admin:admin@localhost:8761/eureka/}


logging:
  level:
    org:
      springframework:
        boot: INFO
        web: INFO

spring:
  security:
    basic:
      enabled: ${DISCOVERY_SECURITY_ENABLED:false}
    user:
      name: ${DISCOVERY_USER_NAME:admin}
      password: ${DISCOVERY_USER_PASSWORD:admin}

