server:
  port: 9001
  max-http-header-size: 1024KB
spring:
  cloud:
    gateway:
      default-filter:
        - TokenRelay
      routes:
        - id: program-service
          uri: lb://card-product-service
          predicates:
            - Path=/cardProduct/**
          filters:
            - TagBiometricGatewayFilter
            - TokenRelay=
            - RemoveResponseHeader=Server
            - name: CircuitBreaker
              args:
                name: programCircuitBreaker
                fallbackUri: forward:/fallback/programFallback
        - id: client-service
          uri: lb://client-service
          predicates:
            - Path=/clients/**
          filters:
            - TagBiometricGatewayFilter
            - TokenRelay=
            - RemoveResponseHeader=Server
            - name: CircuitBreaker
              args:
                name: clientCircuitBreaker
                fallbackUri: forward:/fallback/clientFallback
        - id: diva-service
          uri: lb://diva-service
          predicates:
            - Path=/diva/**
          filters:
            - TagBiometricGatewayFilter
            - TokenRelay=
            - RemoveResponseHeader=Server
            - name: CircuitBreaker
              args:
                name: clientCircuitBreaker
                fallbackUri: forward:/fallback/clientFallback
        - id: profile-service
          uri: lb://card-holder-service
          predicates:
            - Path=/cardHolder/**
          filters:
            - TagBiometricGatewayFilter
            - TokenRelay=
            - RemoveResponseHeader=Server
            - name: CircuitBreaker
              args:
                name: profileCircuitBreaker
                fallbackUri: forward:/fallback/profileFallback
        - id: account-service
          uri: lb://card-service
          predicates:
            - Path=/cards/**
          filters:
            - TagBiometricGatewayFilter
            - TokenRelay=
            - RemoveResponseHeader=Server
            - name: CircuitBreaker
              args:
                name: accountCircuitBreaker
                fallbackUri: forward:/fallback/accountFallback
        - id: processor-service
          uri: lb://processor-service
          predicates:
            - Path=/processors/**
          filters:
            - TagBiometricGatewayFilter
            - TokenRelay=
            - RemoveResponseHeader=Server
            - name: CircuitBreaker
              args:
                name: processorCircuitBreaker
                fallbackUri: forward:/fallback/processorFallback
        - id: usermanagement-service
          uri: lb://usermanagement-service
          predicates:
            - Path=/usermanagement/**
          filters:
            - TagBiometricGatewayFilter
            - TokenRelay=
            - RemoveResponseHeader=Server
            - name: CircuitBreaker
              args:
                name: userManagementCircuitBreaker
                fallbackUri: forward:/fallback/userManagementFallback
        - id: marqeta-service
          uri: lb://marqeta-service
          predicates:
            - Path=/mqa/**
          filters:
            - TagBiometricGatewayFilter
            - TokenRelay=
            - RemoveResponseHeader=Server
            - name: CircuitBreaker
              args:
                name: marqetaCircuitBreaker
                fallbackUri: forward:/fallback/marqetaFallback
        - id: webhook-service
          uri: lb://webhook-service
          predicates:
            - Path=/webhook/**
          filters:
            - TagBiometricGatewayFilter
            - TokenRelay=
            - RemoveResponseHeader=Server
            - name: CircuitBreaker
              args:
                name: webhookCircuitBreaker
                fallbackUri: forward:/fallback/webhookFallback
        - id: jit-service
          uri: lb://jit-service
          predicates:
            - Path=/jit/**
          filters:
            - TagBiometricGatewayFilter
            - TokenRelay=
            - RemoveResponseHeader=Server
            - name: CircuitBreaker
              args:
                name: jitCircuitBreaker
                fallbackUri: forward:/fallback/jitFallback
        - id: three-ds-service
          uri: lb://three-ds-service
          predicates:
            - Path=/three-ds/**
          filters:
            - TagBiometricGatewayFilter
            - TokenRelay=
            - RemoveResponseHeader=Server
            - name: CircuitBreaker
              args:
                name: threeDsCircuitBreaker
                fallbackUri: forward:/fallback/threeDsFallback
        - id: tokenization-service
          uri: lb://tokenization-service
          predicates:
            - Path=/tokenization/**
          filters:
            - TagBiometricGatewayFilter
            - TokenRelay=
            - RemoveResponseHeader=Server
            - name: CircuitBreaker
              args:
                name: tokenizationCircuitBreaker
                fallbackUri: forward:/fallback/tokenizationFallback

        - id: usermanagement-service-v1
          uri: lb://usermanagement-service
          predicates:
            - Path=/v1/usermanagement/**
          filters:
            - RewritePath=/v1/usermanagement/(?<remaining>.*), /usermanagement/${remaining}
            - TagBiometricGatewayFilter
            - TokenRelay=
            - RemoveResponseHeader=Server
            - name: CircuitBreaker
              args:
                name: userManagementCircuitBreaker
                fallbackUri: forward:/fallback/userManagementFallback
        - id: program-service-v1
          uri: lb://card-product-service
          predicates:
            - Path=/v1/cardProduct/**
          filters:
            - RewritePath=/v1/cardProduct/(?<remaining>.*), /cardProduct/${remaining}
            - TagBiometricGatewayFilter
            - TokenRelay=
            - RemoveResponseHeader=Server
            - name: CircuitBreaker
              args:
                name: programCircuitBreaker
                fallbackUri: forward:/fallback/programFallback
        - id: client-service-v1
          uri: lb://client-service
          predicates:
            - Path=/v1/clients/**
          filters:
            - RewritePath=/v1/clients/(?<remaining>.*), /clients/${remaining}
            - TagBiometricGatewayFilter
            - TokenRelay=
            - RemoveResponseHeader=Server
            - name: CircuitBreaker
              args:
                name: clientCircuitBreaker
                fallbackUri: forward:/fallback/clientFallback
        - id: diva-service-v1
          uri: lb://diva-service
          predicates:
            - Path=/v1/diva/**
          filters:
            - RewritePath=/v1/diva/(?<remaining>.*), /diva/${remaining}
            - TagBiometricGatewayFilter
            - TokenRelay=
            - RemoveResponseHeader=Server
            - name: CircuitBreaker
              args:
                name: clientCircuitBreaker
                fallbackUri: forward:/fallback/clientFallback
        - id: profile-service-v1
          uri: lb://card-holder-service
          predicates:
            - Path=/v1/cardHolder/**
          filters:
            - RewritePath=/v1/cardHolder/(?<remaining>.*), /cardHolder/${remaining}
            - TagBiometricGatewayFilter
            - TokenRelay=
            - RemoveResponseHeader=Server
            - name: CircuitBreaker
              args:
                name: profileCircuitBreaker
                fallbackUri: forward:/fallback/profileFallback
        - id: account-service-v1
          uri: lb://card-service
          predicates:
            - Path=/v1/cards/**
          filters:
            - RewritePath=/v1/cards/(?<remaining>.*), /cards/${remaining}
            - TagBiometricGatewayFilter
            - TokenRelay=
            - RemoveResponseHeader=Server
            - name: CircuitBreaker
              args:
                name: accountCircuitBreaker
                fallbackUri: forward:/fallback/accountFallback
        - id: processor-service-v1
          uri: lb://processor-service
          predicates:
            - Path=/v1/processors/**
          filters:
            - RewritePath=/v1/processors/(?<remaining>.*), /processors/${remaining}
            - TagBiometricGatewayFilter
            - TokenRelay=
            - RemoveResponseHeader=Server
            - name: CircuitBreaker
              args:
                name: processorCircuitBreaker
                fallbackUri: forward:/fallback/processorFallback
        - id: marqeta-service-v1
          uri: lb://marqeta-service
          predicates:
            - Path=/v1/mqa/**
          filters:
            - RewritePath=/v1/mqa/(?<remaining>.*), /mqa/${remaining}
            - TagBiometricGatewayFilter
            - TokenRelay=
            - RemoveResponseHeader=Server
            - name: CircuitBreaker
              args:
                name: marqetaCircuitBreaker
                fallbackUri: forward:/fallback/marqetaFallback
        - id: webhook-service-v1
          uri: lb://webhook-service
          predicates:
            - Path=/v1/webhook/**
          filters:
            - RewritePath=/v1/webhook/(?<remaining>.*), /webhook/${remaining}
            - TagBiometricGatewayFilter
            - TokenRelay=
            - RemoveResponseHeader=Server
            - name: CircuitBreaker
              args:
                name: webhookCircuitBreaker
                fallbackUri: forward:/fallback/webhookFallback
        - id: jit-service-v1
          uri: lb://jit-service
          predicates:
            - Path=/v1/jit/**
          filters:
            - RewritePath=/v1/jit/(?<remaining>.*), /jit/${remaining}
            - TagBiometricGatewayFilter
            - TokenRelay=
            - RemoveResponseHeader=Server
            - name: CircuitBreaker
              args:
                name: jitCircuitBreaker
                fallbackUri: forward:/fallback/jitFallback
        - id: three-ds-service-v1
          uri: lb://three-ds-service
          predicates:
            - Path=/v1/three-ds/**
          filters:
            - RewritePath=/v1/three-ds/(?<remaining>.*), /three-ds/${remaining}
            - TagBiometricGatewayFilter
            - TokenRelay=
            - RemoveResponseHeader=Server
            - name: CircuitBreaker
              args:
                name: threeDsCircuitBreaker
                fallbackUri: forward:/fallback/threeDsFallback
        - id: tokenization-service-v1
          uri: lb://tokenization-service
          predicates:
            - Path=/v1/tokenization/**
          filters:
            - RewritePath=/v1/tokenization/(?<remaining>.*), /tokenization/${remaining}
            - TagBiometricGatewayFilter
            - TokenRelay=
            - RemoveResponseHeader=Server
            - name: CircuitBreaker
              args:
                name: tokenizationCircuitBreaker
                fallbackUri: forward:/fallback/tokenizationFallback

  security:
    oauth2:
      client:
        provider:
          keycloak:
            token-uri: ${KEYCLOAK_HOST:https://keycloak-tag-pay-qa.devtomaster.com}/realms/tag-biometric/protocol/openid-connect/token
            issuer-uri: ${KEYCLOAK_HOST:https://keycloak-tag-pay-qa.devtomaster.com}/realms/tag-biometric
            jwk-set-uri: ${KEYCLOAK_HOST:http://localhost:8080}/realms/tag-biometric/protocol/openid-connect/certs
            user-info-authentication-method: header
            admin-cli: ${KEYCLOAK_CLIENT_ID:admin-cli}
            auth-server-url: ${AUTH_SERVER_URL:http://localhost:8080/}
            realm: ${KEYCLOAK_REALM:tag-biometric}
            realm-bcaas: ${KEYCLOAK_INTERNAL_REALM:bcaas-internal}
            realm-bcaas-clientSecret: ${KEYCLOAK_INTERNAL_CLIENT_SECRET:cukK8heAjhzPOe3ff8hhzIQmnqjMdHR4}
            clientSecret: ${KEYCLOAK_CLIENT_SECRET:1rnbod8iDEcDjX4guTvM9mDG7g0nnz9I}
            webhook-url: ${WEBHOOK_URL:/webhook/mqa}
            jit-funding-url: ${JIT_FUNDING_URL:/jit/mqa/gateway/mqa}
            three-ds-url: ${THREE_DS_URL:/three-ds/challenge-result}
            authentication-response-url: ${AUTHENTICATION_RESPONSE_URL:/three-ds/authentication-result}
            authentication-request-url: ${AUTHENTICATION_REQUEST_URL:/three-ds/authentication}
            authorization: Authorization
        registration:
          tag-pay-gateway-client:
            provider: keycloak
            client-id: ${KEYCLOAK_RESOURCE:gateway-service}
            client-secret: ${KEYCLOAK_CLIENT_SECRET:1rnbod8iDEcDjX4guTvM9mDG7g0nnz9I}
            authorization-grant-type: authorization_code
            redirect-uri: ${KEYCLOAK_HOST:http://localhost:8080}/login/oauth2/code/keycloak

encryption:
  value: false
  key: Thisisatestkeyfortesting

logstash:
  url: ${LOGSTASH_URL:localhost:5000}
  show-logs: ${SHOW_LOGS:false}

eureka:
  instance:
    prefer-ip-address: ${EUREKA_INSTANCE_IP_STATUS:false}
  client:
    registryFetchIntervalSeconds: ${REGISTRY_FETCH_INTERVAL_SECONDS:15}
    serviceUrl:
      defaultZone: ${DISCOVERY_URL:http://admin:admin@localhost:8761/eureka/}

keycloak-details:
  user: ${KEYCLOAK_USERNAME:admin}
  pass: ${KEYCLOAK_PASSWORD:admin}
  client-id: ${KEYCLOAK_CLIENT_ID:admin-cli}
  realm-master: ${KEYCLOAK_REALM_MASTER:master}

logging:
  level:
    org:
      springframework:
        boot:
          autoconfigure:
            security: ERROR

rate-limiter:
  limit: ${RATE_LIMITER_LIMIT:1000}

email-notification:
  smtp-host: ${SMTP_HOST_INTERNAL_SERVER:smtp.gmail.com}
  smtp-port: ${SMTP_PORT_INTERNAL_SERVER:587}
  smtp-username: ${SMTP_USERNAME_INTERNAL_SERVER:farsin.workk@gmail.com}
  smtp-password: ${SMTP_PASSWORD_INTERNAL_SERVER:guygqrnnddshenab}
  smtp-email-from: ${SMTP_EMAIL_FROM_INTERNAL_SERVER:farsin@tagbiometrics.com}
  smtp-email-subject: ${SMTP_EMAIL_SUBJECT_INTERNAL_SERVER:Internal Server Error}
  tag-username: ${TAG_USERNAME:TagBiometrics}
  tag-email: ${TAG_EMAIL:farsin@tagbiometrics.com}

health-check:
  card-holder-service: http://card-holder-service/cardHolder/actuator/health
  card-management-service: http://card-service/cards/actuator/health
  card-product-service: http://card-product-service/cardProduct/actuator/health
  client-service: http://client-service/clients/actuator/health
  processor-service: http://processor-service/processors/actuator/health
  three-de-service: http://three-ds-service/three-ds/actuator/health
  tokenization-service: http://tokenization-service/tokenization/actuator/health
  user-management-service: http://usermanagement-service/usermanagement/actuator/health
  webhook-service: http://webhook-service/webhook/actuator/health

health-check-request:
  send-health-check: false
  initial-delay: 600000
  fixed-rate: 300000

zipkin:
  tracing:
    endpoint: ${ZIPKIN_URL:http://localhost:9411}/api/v2/spans